# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CameraParam.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43\x61meraParam.proto\x12\x0b\x63\x61meraparam\"\x1d\n\x0c\x44istortParam\x12\r\n\x05param\x18\x01 \x03(\x02\"W\n\x0fInstrinsicParam\x12\x0f\n\x07\x66ocal_u\x18\x01 \x01(\x02\x12\x0f\n\x07\x66ocal_v\x18\x02 \x01(\x02\x12\x10\n\x08\x63\x65nter_u\x18\x03 \x01(\x02\x12\x10\n\x08\x63\x65nter_v\x18\x04 \x01(\x02\"h\n\x0e\x45xtrinsicParam\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x0b\n\x03yaw\x18\x04 \x01(\x02\x12\r\n\x05pitch\x18\x05 \x01(\x02\x12\x0c\n\x04roll\x18\x06 \x01(\x02\x12\x0b\n\x03\x66ov\x18\x07 \x01(\x02\"1\n\x08VCSParam\x12\x10\n\x08rotation\x18\x01 \x01(\x02\x12\x13\n\x0btranslation\x18\x02 \x01(\x02\"7\n\nImageParam\x12\x13\n\x0bimage_width\x18\x01 \x01(\r\x12\x14\n\x0cimage_heigth\x18\x02 \x01(\rB\x1a\n\x18\x63om.mx.datacollect.protob\x06proto3')



_DISTORTPARAM = DESCRIPTOR.message_types_by_name['DistortParam']
_INSTRINSICPARAM = DESCRIPTOR.message_types_by_name['InstrinsicParam']
_EXTRINSICPARAM = DESCRIPTOR.message_types_by_name['ExtrinsicParam']
_VCSPARAM = DESCRIPTOR.message_types_by_name['VCSParam']
_IMAGEPARAM = DESCRIPTOR.message_types_by_name['ImageParam']
DistortParam = _reflection.GeneratedProtocolMessageType('DistortParam', (_message.Message,), {
  'DESCRIPTOR' : _DISTORTPARAM,
  '__module__' : 'CameraParam_pb2'
  # @@protoc_insertion_point(class_scope:cameraparam.DistortParam)
  })
_sym_db.RegisterMessage(DistortParam)

InstrinsicParam = _reflection.GeneratedProtocolMessageType('InstrinsicParam', (_message.Message,), {
  'DESCRIPTOR' : _INSTRINSICPARAM,
  '__module__' : 'CameraParam_pb2'
  # @@protoc_insertion_point(class_scope:cameraparam.InstrinsicParam)
  })
_sym_db.RegisterMessage(InstrinsicParam)

ExtrinsicParam = _reflection.GeneratedProtocolMessageType('ExtrinsicParam', (_message.Message,), {
  'DESCRIPTOR' : _EXTRINSICPARAM,
  '__module__' : 'CameraParam_pb2'
  # @@protoc_insertion_point(class_scope:cameraparam.ExtrinsicParam)
  })
_sym_db.RegisterMessage(ExtrinsicParam)

VCSParam = _reflection.GeneratedProtocolMessageType('VCSParam', (_message.Message,), {
  'DESCRIPTOR' : _VCSPARAM,
  '__module__' : 'CameraParam_pb2'
  # @@protoc_insertion_point(class_scope:cameraparam.VCSParam)
  })
_sym_db.RegisterMessage(VCSParam)

ImageParam = _reflection.GeneratedProtocolMessageType('ImageParam', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEPARAM,
  '__module__' : 'CameraParam_pb2'
  # @@protoc_insertion_point(class_scope:cameraparam.ImageParam)
  })
_sym_db.RegisterMessage(ImageParam)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.mx.datacollect.proto'
  _DISTORTPARAM._serialized_start=34
  _DISTORTPARAM._serialized_end=63
  _INSTRINSICPARAM._serialized_start=65
  _INSTRINSICPARAM._serialized_end=152
  _EXTRINSICPARAM._serialized_start=154
  _EXTRINSICPARAM._serialized_end=258
  _VCSPARAM._serialized_start=260
  _VCSPARAM._serialized_end=309
  _IMAGEPARAM._serialized_start=311
  _IMAGEPARAM._serialized_end=366
# @@protoc_insertion_point(module_scope)
